def save_from_to(from_path, to_path):                                                                                                                                    
    cap = cv2.VideoCapture(from_path)                                                                                                                                        # Define the codec and create VideoWriter object                                                                                                                     
    fourcc = cv2.VideoWriter_fourcc(*'H264')                                                                                                                             
    out = cv2.VideoWriter(to_path,fourcc, 20.0, (2192,2192))                                                                                                                 while(cap.isOpened()):                                                                                                                                               
        ret, frame = cap.read()                                                                                                                                          
        if ret==True:                                                                                                                                                    
            out.write(frame)                                                                                                                                                         cv2.imshow('frame',frame)                                                                                                                                    
            if cv2.waitKey(1) & 0xFF == ord('q'):                                                                                                                        
                break                                                                                                                                                    
        else:                                                                                                                                                            
            break                                                                                                                                                            # Release everything if job is finished                                                                                                                              
    cap.release()                                                                                                                                                        
    out.release()                                                                                                                                                        
    cv2.destroyAllWindows()  
